/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FooterNav: typeof import('./src/components/FooterNav.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroBanner: typeof import('./src/components/HeroBanner.vue')['default']
    PoemCard: typeof import('./src/components/PoemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesCard: typeof import('./src/components/SeriesCard.vue')['default']
    TagCloud: typeof import('./src/components/TagCloud.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
