// 按官方 XMind 数据结构生成合成 ZIP；只在独立本机资料中验收，不访问云端。
import {chromium} from 'playwright-core';import JSZip from 'jszip';import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import {readFile} from 'node:fs/promises';
const url=process.argv[2]||'http://127.0.0.1:3004/qingxiaolu/';
const svg='<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>';
const root={id:'root',title:'现代大纲',notes:{plain:{content:''},html:{content:{paragraphs:[{spans:[{text:'第一段'},{href:'https://example.com/source',spans:[{text:'资料来源'}]},{image:'xap:resources/picture.svg'}]},{spans:[{text:'第二段📝'}]}]}}},children:{attached:[{id:'chapter',title:'第一章',notes:{plain:{content:'章节备注'}}}],detached:[{id:'idea',title:'游离灵感'}],summary:[{id:'summary',title:'阶段概要',notes:{plain:{content:'阶段正文'}}}],callout:[{id:'callout',title:'人物标注',notes:{plain:{content:'标注正文'}}}]}};
const chapterPng=await readFile(new URL('fixtures/android-forward/images/image-0.png',import.meta.url));
root.children.attached[0].image={src:'xap:resources/chapter.png'};
root.children.detached[0].image={src:'xap:resources/missing.png'};
const jsonZip=new JSZip();jsonZip.file('content.json',JSON.stringify([{id:'sheet',rootTopic:root}]));jsonZip.file('resources/picture.svg',svg);jsonZip.file('resources/chapter.png',chapterPng);jsonZip.file('metadata.json','{"dataStructureVersion":"2"}');
const modern=await jsonZip.generateAsync({type:'nodebuffer',compression:'DEFLATE'});
const legacyJpg=await readFile(new URL('fixtures/android-forward/images/original.jpg',import.meta.url));
const xmlZip=new JSZip();xmlZip.file('content.xml','<?xml version="1.0" encoding="UTF-8"?><xmap-content xmlns="urn:xmind:xmap:xmlns:content:2.0" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:h="http://www.w3.org/1999/xhtml"><sheet id="legacy-sheet"><topic id="legacy-root"><title>旧版大纲</title><xhtml:img xhtml:src="xap:resources/legacy-root.jpg"/><notes><plain>旧主备注</plain><html><xhtml:p>旧主备注</xhtml:p></html></notes><children><topics type="attached"><topic id="legacy-chapter"><title>旧版章节</title><notes><html><h:p>旧备注第一段</h:p>\n<h:p>旧备注第二段<h:img h:src="xap:resources/legacy-note.svg"/><h:img h:src="xap:resources/broken.png"/></h:p></html></notes></topic></topics></children></topic></sheet></xmap-content>');xmlZip.file('resources/legacy-root.jpg',legacyJpg);xmlZip.file('resources/legacy-note.svg',svg);xmlZip.file('resources/broken.png',Buffer.from([137,80,78,71,13,10,26,10]));
const legacy=await xmlZip.generateAsync({type:'nodebuffer',compression:'DEFLATE'});
const hash=v=>createHash('sha256').update(v).digest('hex');const expectedNote='第一段资料来源（https://example.com/source）\n第二段📝';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext(),page=await context.newPage();await context.route('**/qingxiaolu-api/**',r=>r.abort());await page.goto(url);await page.getByRole('button',{name:'先在本机使用',exact:true}).click();await page.getByRole('button',{name:/导入本地文档/}).click();
 await page.locator('input[type=file]').setInputFiles([{name:'现代导图.xmind',mimeType:'application/x-xmind',buffer:modern},{name:'旧版导图.xmind',mimeType:'application/x-xmind',buffer:legacy}]);await page.getByRole('heading',{name:'临时预览',exact:true}).waitFor();
 const modernCard=page.locator('.candidate-list article').filter({has:page.locator('input[value="现代导图"]')}),legacyCard=page.locator('.candidate-list article').filter({has:page.locator('input[value="旧版导图"]')});
 const text=await modernCard.locator('textarea').inputValue();
 if(process.argv.includes('--observe')) { await page.waitForFunction(()=>[...document.querySelectorAll('.candidate-images img')].every(image=>image.complete));console.log(JSON.stringify({objectPlaceholder:text.includes('[object Object]'),summaryPresent:text.includes('阶段概要'),calloutPresent:text.includes('人物标注'),legacyText:await legacyCard.locator('textarea').inputValue(),previewImages:await modernCard.locator('.candidate-images img').count(),legacyImages:await legacyCard.locator('.candidate-images img').count(),brokenPreviewImages:await legacyCard.locator('.candidate-images img').evaluateAll(images=>images.filter(image=>image.naturalWidth===0).length)}));}
 else{
  assert.ok(text.includes(expectedNote.split('\n')[0]));assert.ok(!text.includes('[object Object]'));assert.ok(text.includes('阶段概要')&&text.includes('人物标注'));assert.ok((await legacyCard.locator('textarea').inputValue()).includes('旧备注第二段'));
  const svgData='data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64'),pngData='data:image/png;base64,'+chapterPng.toString('base64');
  const jpegData='data:image/jpeg;base64,'+legacyJpg.toString('base64');
  assert.deepEqual(await legacyCard.locator('.candidate-images img').evaluateAll(images=>images.map(image=>image.src)),[jpegData,svgData]);
  const legacyText=await legacyCard.locator('textarea').inputValue();assert.equal((legacyText.match(/旧主备注/g)||[]).length,1);assert.ok(legacyText.includes('旧备注第一段\n    \n    旧备注第二段'));
  await legacyCard.getByText('有 1 处导图图片无法读取，原始 XMind 已保留，请下载原文件核对。',{exact:true}).waitFor();
  assert.deepEqual(await modernCard.locator('.candidate-images img').evaluateAll(images=>images.map(image=>image.src)),[svgData,pngData]);
  await page.waitForFunction(()=>[...document.querySelectorAll('.candidate-images img')].every(image=>image.complete&&image.naturalWidth>0));
  await modernCard.getByText('有 1 处导图图片无法读取，原始 XMind 已保留，请下载原文件核对。',{exact:true}).waitFor();
  const verifyDownload=async(locator,bytes)=>{const event=page.waitForEvent('download');await locator.click();const download=await event;assert.equal(hash(await readFile(await download.path())),hash(bytes));};
  await verifyDownload(modernCard.getByRole('link',{name:'下载原始 XMind 核对',exact:true}),modern);await verifyDownload(legacyCard.getByRole('link',{name:'下载原始 XMind 核对',exact:true}),legacy);
  await page.getByText('预览已保存在本机，刷新可恢复',{exact:true}).waitFor();await page.reload();assert.equal(await modernCard.locator('textarea').inputValue(),text);
  await modernCard.getByRole('button',{name:'按导图节点拆分',exact:true}).click();await legacyCard.getByRole('button',{name:'按导图节点拆分',exact:true}).click();assert.equal(await page.locator('.candidate-list article').count(),7);
  assert.equal(await page.locator('.candidate-list article').filter({has:page.locator('input[value="现代大纲"]')}).locator('img').getAttribute('src'),svgData);
  assert.equal(await page.locator('.candidate-list article').filter({has:page.locator('input[value="第一章"]')}).locator('img').getAttribute('src'),pngData);
  assert.equal(await page.locator('.candidate-list article').filter({has:page.locator('input[value="旧版大纲"]')}).locator('img').getAttribute('src'),jpegData);
  assert.equal(await page.locator('.candidate-list article').filter({has:page.locator('input[value="旧版章节"]')}).locator('img').getAttribute('src'),svgData);
  await page.getByText('预览已保存在本机，刷新可恢复',{exact:true}).waitFor();await page.getByRole('button',{name:'正式导入已选内容（7）',exact:true}).click();await page.getByText('已正式导入 7 条内容',{exact:true}).waitFor();await page.getByRole('button',{name:'稿件库',exact:true}).click();assert.equal(await page.locator('article[data-blog-month]').count(),7);
  const noteCard=page.locator('article[data-blog-month]').filter({has:page.getByRole('heading',{name:'现代大纲',exact:true})});await verifyDownload(noteCard.getByRole('link',{name:'下载原始 XMind',exact:true}),modern);await noteCard.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByPlaceholder('这一刻，想写点什么……').inputValue(),expectedNote);await page.reload();assert.equal(await page.getByPlaceholder('这一刻，想写点什么……').inputValue(),expectedNote);
  await page.getByRole('button',{name:'设置',exact:true}).click();const backupEvent=page.waitForEvent('download');await page.getByRole('button',{name:/下载完整备份/}).click();const backup=JSON.parse(await readFile(await (await backupEvent).path(),'utf8'));const modernSaved=backup.items.find(v=>v.payload.title==='现代大纲');assert.equal(hash(Buffer.from(modernSaved.payload.content.importRaw.originalXmind.split(',')[1],'base64')),hash(modern));
  assert.equal(modernSaved.payload.content.images[0],svgData);assert.equal(backup.items.find(v=>v.payload.title==='第一章').payload.content.images[0],pngData);
  assert.equal(backup.items.find(v=>v.payload.title==='旧版大纲').payload.content.images[0],jpegData);
  assert.equal(backup.items.find(v=>v.payload.title==='旧版章节').payload.content.images[0],svgData);
  const materialContext=await browser.newContext(),target=await materialContext.newPage();await materialContext.route('**/qingxiaolu-api/**',r=>r.abort());await target.goto(url);await target.getByRole('button',{name:'先在本机使用',exact:true}).click();await target.getByPlaceholder('新项目名称').fill('导图归档项目');await target.getByRole('button',{name:'新建',exact:true}).click();await target.getByRole('heading',{name:'导图归档项目',exact:true}).waitFor();await target.getByRole('button',{name:/导入本地文档/}).click();await target.locator('input[type=file]').setInputFiles({name:'现代导图.xmind',mimeType:'application/x-xmind',buffer:modern});await target.getByRole('button',{name:'按导图节点拆分',exact:true}).click();await target.locator('.import-destination select').nth(0).selectOption({label:'导图归档项目'});await target.locator('.import-destination select').nth(1).selectOption('大纲');await target.getByRole('button',{name:'正式导入已选内容（5）',exact:true}).click();await target.getByText('已正式导入 5 条内容',{exact:true}).waitFor();
  await target.getByRole('button',{name:'项目',exact:true}).click();await target.getByRole('heading',{name:'导图归档项目',exact:true}).click();await target.locator('.project-section-tabs').getByRole('button',{name:'大纲',exact:true}).click();await target.locator('.reader-images img').waitFor();assert.equal(await target.locator('.reader-images img').getAttribute('src'),svgData);await target.locator('.outline-reader').getByRole('button',{name:'下一章',exact:true}).click();await target.waitForFunction(src=>document.querySelector('.reader-images img')?.getAttribute('src')===src,pngData);await target.locator('.outline-reader').getByRole('button',{name:'上一章',exact:true}).click();await target.locator('.outline-reader').getByRole('button',{name:'编辑',exact:true}).click();await target.locator('.chapter-card').first().waitFor();assert.equal(await target.locator('.chapter-card').count(),5);assert.equal(await target.locator('.chapter-card').filter({has:target.locator('input[value="现代大纲"]')}).locator('textarea').inputValue(),expectedNote);
  await target.reload();await target.getByRole('button',{name:'项目',exact:true}).click();await target.getByRole('heading',{name:'导图归档项目',exact:true}).click();await target.locator('.project-section-tabs').getByRole('button',{name:'大纲',exact:true}).click();await target.locator('.reader-images img').waitFor();assert.equal(await target.locator('.reader-images img').getAttribute('src'),svgData);await target.locator('.outline-reader').getByRole('button',{name:'下一章',exact:true}).click();await target.waitForFunction(src=>document.querySelector('.reader-images img')?.getAttribute('src')===src,pngData);await target.locator('.outline-reader').getByRole('button',{name:'上一章',exact:true}).click();await target.locator('.outline-reader').getByRole('button',{name:'编辑',exact:true}).click();await target.locator('.chapter-card').first().waitFor();assert.equal(await target.locator('.chapter-card').count(),5);assert.equal(await target.locator('.chapter-card').filter({has:target.locator('input[value="现代大纲"]')}).locator('textarea').inputValue(),expectedNote);await target.locator('.project-section-tabs').getByRole('button',{name:'导出',exact:true}).click();await target.getByText('导入原文件（1）',{exact:true}).click();const originalEvent=target.waitForEvent('download');await target.getByRole('link',{name:'下载原始 XMind：现代导图.xmind',exact:true}).click();assert.equal(hash(await readFile(await (await originalEvent).path())),hash(modern));
  await target.locator('.project-section-tabs').getByRole('button',{name:'大纲',exact:true}).click();await target.locator('.outline-reader, .chapter-card').first().waitFor();if(await target.locator('.outline-reader').count())await target.locator('.outline-reader').getByRole('button',{name:'编辑',exact:true}).click();await target.locator('.chapter-card').filter({has:target.locator('input[value="现代大纲"]')}).getByRole('button',{name:'写本章正文',exact:true}).click();await target.getByPlaceholder('稿件标题（可选）').fill('带插图的章节正文');await target.getByPlaceholder('这一刻，想写点什么……').fill('正文与原图一起阅读');await target.locator('input[type=file][accept="image/*"]').setInputFiles({name:'chapter.png',mimeType:'image/png',buffer:chapterPng});await target.locator('.qzone-images.compact img').waitFor();await target.getByRole('button',{name:'保存',exact:true}).click();await target.getByText('已保存到本机，可以继续写作',{exact:true}).waitFor();await target.getByRole('button',{name:'项目',exact:true}).click();await target.getByRole('heading',{name:'导图归档项目',exact:true}).click();await target.locator('.project-section-tabs').getByRole('button',{name:'大纲',exact:true}).click();await target.locator('.reader-linked-article img').waitFor();assert.equal(await target.locator('.reader-linked-article img').getAttribute('src'),pngData);
  console.log(JSON.stringify({richNotesAndParagraphs:true,summaryAndCalloutRetained:true,legacyXmlNotes:true,legacyNotesNotDuplicated:true,legacyParagraphs:true,legacyNamespacedImages:true,corruptImageWarning:true,originalArchivesExact:true,previewReload:true,splitSevenNodes:true,formalImport:true,editAndReloadExact:true,completeBackupKeepsOriginal:true,projectOutlineFiveNodes:true,projectOutlineReload:true,projectOriginalDownload:true,originalImageBytes:true,nodeImageOwnership:true,missingImageWarning:true,readerImagesBeforeAndAfterReload:true,linkedChapterImage:true,syntheticFixturesOnly:true}));
 }
}finally{await browser.close();}
